### ISSUE TITLE
Import text snippets should not appear if a compatible interface isn't selected

### ISSUE THREAD

**Issue by CedricJean** [UniversalDataTool/universal-data-tool#150]
It is not disbled when the type of project use other type of data than texte

**Comment by seveibar** [comment]
that's a good idea

**Comment by CedricJean** [comment]
In fact it cause some bug when we use it outside its context and we can also think about hiding non usable import so our interface will become more light

**Comment by seveibar** [comment]
somewhat related: the loose plan is to have a search feature on the import page because we'll have hundreds of ways to import data to build a dataset. I think hiding import buttons could confuse people, but we could disable them and move them to the bottom so that enabled buttons always appear first

**Comment by CedricJean** [comment]
and we should put them in alphabetical order
