### ISSUE TITLE
Prevent the localStorage to update when no change is done in the annotations

### ISSUE THREAD

**Issue by CedricJean** [UniversalDataTool/universal-data-tool#93]
The localStorage is contain in the var recentItems and this var update when we click on the button next and prev without anyregard on the fact we actually change something.

**Comment by seveibar** [comment]
Is this primarily a performance concern? Like does it get slow if we keep saving to local storage?

**Comment by CedricJean** [comment]
No its not a concern for performance now. Like what it is written on slack its because the feature i develop need to use an useEffect on the var recentItems and this feature is consumming the performance. If this var who contains the localStorage is updated anytime. When i will merge my feature it can be problematic. Its why i ask on slack if im better to implement it on my fork. And my answer was no so i let you guys do it but if you prefer i can take care of it monday

**Comment by seveibar** [comment]
ohh i see

**Comment by seveibar** [comment]
In your `useEffect`, how are you watching for `recentItems`? I think there's another way to fix this without changing what's saved to `recentItems`, for example consider the following pattern:

```javascript
function myComponent() {
  useEffect(() => {
    veryPerformanceIntenseCode()
  }, [objectThatChangesALot])
```

This pattern happens a lot because objects aren't handled well, however it can be mitigated like this:

```javascript
function myComponent() {
  const lastObjectRef = useRef()
  useEffect(() => {
    if (!hasChanged(lastObjectRef.current, objectThatChangesALot)) return
    lastObjectRef.current = objectThatChangesALot
    veryPerformanceIntenseCode()
  }, [objectThatChangesALot])
```

One way to address a performance concern when watching `recentItems` is to check that the recentItems have changed in a way that is actually signficant, in this case, you don't care whether or not the `taskOutput[sampleIndex] === null` or `Array.isArray(taskOutput[sampleIndex]) && taskOutput[sampleIndex].length === 0`.

So something like this:

```javascript

function hasChanged(a,b) {
  if (a === b) return false
  if (a.taskData !== b.taskData) return true
  // TODO check a.taskOutput vs b.taskOutput, but if the only change is null the same as `[]` in the check
}

function myComponent() {
  const lastRecentItemsRef = useRef()
  useEffect(() => {
    if (!hasChanged(lastObjectRef.current, recentItems)) return
    lastRecentItemsRef.current = objectThatChangesALot
    veryPerformanceIntenseCode()
  }, [recentItems])
```

I would recommend this approach over the API change where "saving" results in `null` instead of `[]`. But I understand why it's easier for a `useEffect` for UDT to handle it.

**Comment by Ownmarc** [comment]
That was our first idea, but since you said that it was not the expected for the recentItem to change when there were actually no change, useEffect on recentItems would work just fine if we fixed the unnecessary trigger of onChangeOHA

**Comment by seveibar** [comment]
Yes to be clear in the slack I misunderstood what was going on, but I've found this dialogue to be helpful to think through how these things work.
